## **import libraries & upload data**

In [103]:
import pandas as pd
import numpy as np

In [104]:
re=pd.read_csv('propertyfinder.csv')

C:\Users\dell\AppData\Local\Temp\ipykernel_2440\3337464109.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  re=pd.read_csv('propertyfinder.csv')

In [105]:
re.drop_duplicates(
    subset=['property_type', 'price_egp', 'lat', 'lon', 'area_value', 'bedrooms', 'bathrooms', 'description'],
    keep='first',
    inplace=True,
    ignore_index=True
)

## **adjust display options**

In [106]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.options.display.float_format = '{:,.2f}'.format

##**creating 2 dataframes**

In [107]:
sell = re[re['category'] == 'buy'].copy()
rent = re[re['category'] == 'rent'].copy()
# sell=pd.read_csv('/content/drive/MyDrive/Sell.csv')
# rent=pd.read_csv('/content/drive/MyDrive/Rent.csv')

In [108]:
columns_to_keep = [###########
    
    'property_type',
    'completion_status',
    'title',
    'price_egp',
    'city',
    'town',
    'district',
    'lat',
    'lon',
    'bedrooms',
    'bathrooms',
    'area_value',
    'furnished',
    'listing_level',
    #'is_premium',
    #'is_featured',
    'listed_date',
    'payment_method',
    'description',
    'agent_id',
    'broker_id',
]
sell=sell[columns_to_keep]
rent=rent[columns_to_keep]

In [109]:
rent #19910 rows

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
19117,Apartment,NaN,First use semi furnished 2BR in El Patio Oro,"35,000.00",Cairo,New Cairo City,The 5th Settlement,30.03,31.59,2,2,128.00,PARTLY,premium,2026-03-04T21:13:08Z,NaN,Apartment with kitchen and air conditioning fo...,"55,901.00","5,389.00"
19118,Apartment,NaN,"Unfurnished apartment for rent with kitchen, a...","50,000.00",Cairo,New Cairo City,El Banafseg,30.05,31.47,3,3,300.00,NO,premium,2026-03-04T12:47:53Z,NaN,E14755 Unfurnished apartment for rent with kit...,"66,449.00","2,520.00"
19119,Apartment,NaN,Furnished apartment for rent in Al Yasmin 2 Vi...,"45,000.00",Cairo,New Cairo City,El Yasmeen,30.05,31.45,3,3,210.00,YES,premium,2026-03-04T11:12:17Z,NaN,E14748 Furnished apartment for rent in Al Yasm...,"66,449.00","2,520.00"
19120,Apartment,NaN,Unfurnished apartment for rent with air condit...,"25,000.00",Cairo,New Cairo City,Abou El Houl,29.98,31.47,2,2,150.00,NO,premium,2026-03-04T10:58:28Z,NaN,E14745 Unfurnished apartment for rent with air...,"50,635.00","2,520.00"
19121,Apartment,NaN,Furnished apartment for rent behind Mirage Cit...,"40,000.00",Cairo,New Cairo City,The 1st Settlement,30.05,31.44,2,2,130.00,YES,premium,2026-03-04T09:19:33Z,NaN,E12494B Furnished apartment for rent behind Mi...,"44,158.00","2,520.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38133,Apartment,NaN,"Furnished apartment for rent in Al Rehab, 250M","55,000.00",Cairo,New Cairo City,Al Rehab,30.06,31.51,3,3,250.00,YES,standard,2026-02-07T16:33:32Z,NaN,Furnished apartment for rent in Al Rehab Phase...,"68,162.00","4,456.00"
38134,Apartment,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,"45,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.09,3,3,180.00,YES,standard,2026-02-07T16:32:23Z,NaN,"AVAILABLE MID AUGUST, 2025 An Elegant 3 Bedroo...","23,636.00",430.00
38135,Townhouse,NaN,Furnished villa for rent in Town 5 rooms near New,"120,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.04,5,5,320.00,YES,standard,2026-02-07T16:31:32Z,NaN,Furnished villa for rent at a special price To...,"16,061.00","4,679.00"
38136,Apartment,NaN,For Rent – Premium 196m² Fully Finished Apartment,"50,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.06,2,2,196.00,NO,standard,2026-02-07T16:29:24Z,NaN,For Rent – Premium 196m² Fully Finished Apartm...,"60,109.00",430.00
38137,Apartment,NaN,If you're looking hotel units contact us now,"75,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.55,2,2,144.00,YES,standard,2026-02-07T16:26:50Z,NaN,Unit Description: Location: Villette Compound ...,"56,917.00","5,307.00"

## **data understanding**

In [110]:
re.shape

(38138, 53)

In [111]:
re.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38138 entries, 0 to 38137
Data columns (total 53 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           38137 non-null  object
 1   internal_id          38137 non-null  float64
 2   category             38138 non-null  object
 3   listing_type         38138 non-null  object
 4   detail_url           38137 non-null  object
 5   property_type        38137 non-null  object
 6   offering_type        38137 non-null  object
 7   completion_status    19079 non-null  object
 8   title                38137 non-null  object
 9   price_egp            38137 non-null  float64
 10  price_period         38137 non-null  object
 11  price_currency       38138 non-null  object
 12  location_full        38137 non-null  object
 13  city                 38137 non-null  object
 14  town                 38137 non-null  object
 15  district             37805 non-null  object
 16  subdistrict          31580 non-null  object
 17  lat                  38137 non-null  float64
 18  lon                  38137 non-null  float64
 19  bedrooms             38105 non-null  object
 20  bathrooms            38110 non-null  object
 21  area_value           38137 non-null  float64
 22  area_unit            38138 non-null  object
 23  furnished            30089 non-null  object
 24  listing_level        38137 non-null  object
 25  is_premium           38138 non-null  bool
 26  is_verified          38138 non-null  bool
 27  is_featured          38138 non-null  bool
 28  is_new_construction  38138 non-null  bool
 29  is_direct_from_dev   38138 non-null  bool
 30  is_exclusive         38138 non-null  bool
 31  listed_date          38137 non-null  object
 32  images_count         38138 non-null  int64
 33  has_view_360         38138 non-null  bool
 34  video_url            201 non-null    object
 35  reference            38137 non-null  object
 36  rera                 0 non-null      float64
 37  description          38137 non-null  object
 38  amenities            38107 non-null  object
 39  payment_method       19252 non-null  object
 40  agent_id             38137 non-null  float64
 41  agent_name           38130 non-null  object
 42  agent_email          38137 non-null  object
 43  agent_is_super       38138 non-null  bool
 44  agent_languages      8851 non-null   object
 45  broker_id            38137 non-null  float64
 46  broker_name          38137 non-null  object
 47  broker_email         37951 non-null  object
 48  broker_phone         37951 non-null  float64
 49  contact_phone        38137 non-null  float64
 50  contact_whatsapp     38137 non-null  float64
 51  contact_email        38137 non-null  object
 52  scraped_at           38138 non-null  object
dtypes: bool(8), float64(11), int64(1), object(33)
memory usage: 13.4+ MB

In [112]:
re.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,"56,009,081.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,"24,500,000.00",sell,EGP,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.53,3,6,445.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T19:15:06Z,6,False,NaN,F7QB31CGWE509V2W7DF2GARB2C,NaN,Garden Villa for Sale – Featured in Lake View ...,Balcony | Built in Wardrobes | Covered Parking...,cash,"58,866.00",pierre osama,pierre.Osama@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,201,801,443.00","20,221,257,340.00",pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,"56,247,925.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,"5,145,000.00",sell,EGP,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West,30.05,31.02,2,2,123.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T11:24:23Z,10,False,NaN,rb304,NaN,For Sale: Finished Apartment with ACs in Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"67,166.00",Rana Bahaa ElDeen,ranoushamer901@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,007,169,666.00","20,221,257,340.00",ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,"56,253,883.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,"10,800,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,250.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T14:03:51Z,13,False,NaN,250pncash,NaN,Palm Hills New Cairo Apartment BUA: 250sqm 4 B...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,"56,250,852.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,"10,500,000.00",sell,EGP,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.54,2,2,136.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T12:38:11Z,11,False,NaN,PPH0852SAB266X6GSVATJP4F0M,NaN,Lake View Residence 136 sqm Fully Finished Ren...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"63,401.00",ebrahim hossam,ebrahim.hossam@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,070,115,211.00","20,221,257,340.00",ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,"55,995,764.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,"19,500,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,255.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T09:45:41Z,17,False,NaN,VillTyM,NaN,Palm Hills New Cairo Type M BUA: 255sqm LAND: ...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007

In [113]:
re.isnull().sum().sort_values(ascending=False)

rera                   38138
video_url              37937
agent_languages        29287
completion_status      19059
payment_method         18886
furnished               8049
subdistrict             6558
district                 333
broker_email             187
broker_phone             187
bedrooms                  33
amenities                 31
bathrooms                 28
agent_name                 8
city                       1
town                       1
contact_email              1
description                1
contact_whatsapp           1
reference                  1
detail_url                 1
agent_email                1
listed_date                1
property_type              1
broker_id                  1
broker_name                1
internal_id                1
offering_type              1
listing_level              1
title                      1
price_egp                  1
area_value                 1
agent_id                   1
price_period               1
lon                        1
lat                        1
contact_phone              1
location_full              1
listing_id                 1
agent_is_super             0
is_verified                0
has_view_360               0
images_count               0
is_exclusive               0
is_direct_from_dev         0
is_new_construction        0
is_featured                0
is_premium                 0
area_unit                  0
price_currency             0
listing_type               0
category                   0
scraped_at                 0
dtype: int64

In [114]:
re.describe()

,internal_id,price_egp,lat,lon,area_value,images_count,rera,agent_id,broker_id,broker_phone,contact_phone,contact_whatsapp
count,"38,137.00","38,137.00","38,137.00","38,137.00","38,137.00","38,138.00",0.00,"38,137.00","38,137.00","37,951.00","38,137.00","38,137.00"
mean,"45,303,354.49","8,132,074.59",29.98,31.31,216.89,12.29,NaN,"53,435.17","4,183.05","151,761,487,068.55","315,702,624,874,628.19","62,689,842,364.36"
std,"18,875,016.29","24,431,133.25",0.59,0.85,617.19,4.85,NaN,"17,873.10","10,197.40","86,218,732,100.04","61,613,332,532,169,304.00","76,670,801,599.68"
min,"2,908,155.00","1,300.00",25.07,25.48,1.00,0.00,NaN,"5,500.00",55.00,"1,000,009,081.00","201,000,001,398.00","20,221,257,340.00"
25%,"52,454,953.00","65,000.00",30.00,31.01,130.00,10.00,NaN,"42,687.00","1,657.00","201,000,137,017.00","201,033,052,227.00","20,221,257,340.00"
50%,"54,761,195.00","733,065.00",30.03,31.50,177.00,11.00,NaN,"57,505.00","4,208.00","201,026,694,777.00","201,102,191,494.00","20,221,257,340.00"
75%,"55,760,330.00","9,500,000.00",30.06,31.55,245.00,14.00,NaN,"68,818.00","5,684.00","201,117,033,304.00","201,145,628,844.00","20,221,257,340.00"
max,"56,493,417.00","1,000,000,000.00",31.50,34.90,"96,600.00",30.00,NaN,"73,845.00","179,957.00","201,558,194,855.00","12,032,281,120,109,799,424.00","201,559,777,173.00"

In [115]:
re.describe(include='object')

,listing_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_period,price_currency,location_full,city,town,district,subdistrict,bedrooms,bathrooms,area_unit,furnished,listing_level,listed_date,video_url,reference,description,amenities,payment_method,agent_name,agent_email,agent_languages,broker_name,broker_email,contact_email,scraped_at
count,38137,38138,38138,38137,38137,38137,19079,38137,38137,38138,38137,38137,38137,37805,31580,38105,38110,38138,30089,38137,38137,201,38137,38137,38107,19252,38130,38137,8851,38137,37951,38137,38138
unique,38137,2,2,38137,19,2,4,32373,2,1,1959,12,67,519,1134,9,9,1,3,3,35032,154,38071,35312,17581,3,2652,2725,30,776,770,2725,4711
top,F7QB31CGWE509V2W7DF2GARB2C,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Apartment,Residential for Sale,completed,Hotel apartment for rent inAlRehab fully furni...,sell,EGP,"Mivida, 5th Settlement Compounds, The 5th Sett...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,3,3,sqm,YES,standard,2026-02-10T13:23:33Z,https://www.youtube.com/watch?v=ouXREODabm0,7,We offer all real estate services in some of t...,Balcony | Built in Wardrobes | Central A/C | C...,cash,FORTUNE REALTY,fourtunerealityeg@gmail.com,English | Arabic,Egypt Best Properties,info@egyptbestproperties.com,fourtunerealityeg@gmail.com,2026-03-05T00:26:34.236156
freq,1,19117,38137,1,24071,19116,9958,206,19116,38138,2282,24844,18901,12488,11180,17485,13619,38138,12199,29758,10,7,5,42,1414,12505,521,521,6415,1432,1432,521,25

In [116]:
re[['internal_id', 'agent_id', 'broker_id',
    'broker_phone', 'contact_phone', 'contact_whatsapp']].nunique()

internal_id         38137
agent_id             2766
broker_id             776
broker_phone          769
contact_phone        2478
contact_whatsapp      421
dtype: int64

In [117]:
re['property_type'].unique()

array(['Duplex', 'Apartment', 'Villa', nan, 'Penthouse', 'Twin House',
       'Townhouse', 'Chalet', 'iVilla', 'Hotel Apartment',
       'Whole Building', 'Half Floor', 'Land', 'Bulk Sale Unit', 'Cabin',
       'Roof', 'Palace', 'Full Floor', 'Bulk Rent Unit', 'Bungalow'],
      dtype=object)

In [118]:
re['completion_status'].unique()

# completed:  (Resale)عقار مكتمل البناء ومباع عن طريق إعادة البيع

# off_plan:  (Resale) عقار قيد الإنشاء أو تحت التخطيط

# completed_primary:  (Primary)عقار مكتمل الجاهزية ومباع مباشرة من الشركة /المطور

# off_plan_primary: عقار تحت الإنشاء ومباع مباشرة من المطور مع خطط سداد.

array(['completed', 'off_plan', nan, 'completed_primary',
       'off_plan_primary'], dtype=object)

### extreme values invastigation

In [119]:
sell.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
497,"113,116.00",Apartment,155.00,3,3,Giza,6 October City,6 October Compounds
85,"130,000.00",Duplex,233.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
87,"130,000.00",Apartment,233.00,3,3,Giza,Sheikh Zayed City,Ivoire
2134,"155,220.00",Apartment,200.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
12781,"200,000.00",Chalet,1.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
223,"300,000.00",Chalet,120.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
11541,"300,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
2785,"303,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
796,"325,000.00",Chalet,1.00,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala
476,"340,000.00",Apartment,106.00,2,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
1339,"345,500.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
1191,"350,000.00",Apartment,20.00,2,2,Cairo,Mostakbal City - Future City,Mostakbal City Compounds
12518,"350,000.00",Chalet,20.00,studio,1,Suez,Al Ain Al Sokhna,IL Monte Galala
1447,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
1468,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
1209,"356,100.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
9176,"360,000.00",Apartment,20.00,2,2,Cairo,New Capital City,New Capital Compounds
18867,"370,000.00",Apartment,20.00,1,1,Cairo,Mostakbal City - Future City,Mostakbal City Compounds
11470,"380,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
12936,"390,000.00",Apartment,20.00,4,4,Cairo,New Cairo City,The 5th Settlement

In [120]:
sell.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
3763,"1,000,000,000.00",Villa,238.00,3,7,North Coast,Ras Al Hekma,Jefaira
6112,"988,888,888.00",Villa,"1,352.00",7,7+,Cairo,Zamalek,Mohamed Mazhar St.
6114,"958,000,000.00",Villa,"1,255.00",6,6,Cairo,Zamalek,El Gezirah St.
10135,"940,000,000.00",Land,"96,600.00",NaN,NaN,Giza,6 October City,Al Wahat Road
13853,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
13854,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
10909,"900,000,000.00",Palace,"4,800.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
6191,"850,000,000.00",Land,"1,100.00",NaN,NaN,Cairo,Garden City,Nile Corniche St.
10939,"844,000,000.00",Palace,"4,810.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
10977,"770,400,000.00",Land,"38,520.00",NaN,NaN,Giza,Sheikh Zayed City,Riviera City
5202,"750,111,111.00",Villa,"1,647.00",7+,7+,Cairo,Garden City,Ahmed Basha St.
6329,"750,000,000.00",Villa,"1,801.00",5,6,Cairo,New Cairo City,El Katameya
9165,"750,000,000.00",Villa,"1,800.00",5,6,Cairo,New Cairo City,El Katameya
13874,"682,125,000.00",Apartment,159.00,3,3,Cairo,New Cairo City,The 5th Settlement
13851,"670,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
3761,"650,000,000.00",Townhouse,138.00,3,4,North Coast,Ras Al Hekma,Jefaira
12138,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi
12140,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi
8652,"427,500,000.00",Villa,"1,000.00",5,7,Cairo,New Cairo City,El Katameya
16085,"427,500,000.00",Villa,"1,000.00",5,7,Cairo,New Cairo City,El Katameya

In [121]:
sell.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
10135,"96,600.00","940,000,000.00",Land,NaN,NaN,Giza,6 October City,Al Wahat Road
10282,"42,000.00","400,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
10977,"38,520.00","770,400,000.00",Land,NaN,NaN,Giza,Sheikh Zayed City,Riviera City
10203,"21,000.00","140,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
17129,"14,000.00","120,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
9693,"12,000.00","350,000,000.00",Land,NaN,NaN,Cairo,New Cairo City,The 5th Settlement
5556,"10,600.00","265,000,000.00",Land,NaN,NaN,North Coast,Al Alamein,NaN
5957,"5,600.00","350,000,000.00",Hotel Apartment,7+,7+,Cairo,Downtown,Qasr El Nil
10939,"4,810.00","844,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
10909,"4,800.00","900,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
7654,"4,000.00","90,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
13851,"4,000.00","670,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
13853,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
13854,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
12691,"3,500.00","250,000,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
15589,"3,000.00","170,000,000.00",Villa,7+,7+,Cairo,New Cairo City,Al Rehab
6133,"2,900.00","93,000,000.00",Whole Building,7+,7+,Cairo,Downtown,NaN
4284,"2,633.00","53,000,000.00",Whole Building,3,7+,Cairo,Garden City,Garden City St.
8431,"2,500.00","297,600,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
4718,"2,200.00","170,000,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya

In [122]:
sell.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
80,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,6th District
153,1.00,"582,800.00",Hotel Apartment,2,2,Cairo,Shorouk City,El Shorouk Compounds
154,1.00,"709,700.00",Hotel Apartment,3,3,Cairo,Shorouk City,El Shorouk Compounds
796,1.00,"325,000.00",Chalet,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala
7726,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7758,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7769,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7791,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,17th District
7819,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
9062,1.00,"673,000.00",Hotel Apartment,1,1,Cairo,El Nozha,Sheraton Al Matar
9137,1.00,"497,209.00",Penthouse,1,2,Cairo,New Cairo City,The 5th Settlement
9307,1.00,"1,350,000.00",Chalet,3,3,Suez,Al Ain Al Sokhna,La Vista
9440,1.00,"4,100,000.00",Duplex,2,2,Cairo,New Cairo City,The 5th Settlement
11970,1.00,"4,000,000.00",Chalet,2,2,North Coast,Ras Al Hekma,Jefaira
11973,1.00,"5,660,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road
12448,1.00,"5,400,000.00",Twin House,4,4,Cairo,Shorouk City,El Shorouk Compounds
12781,1.00,"200,000.00",Chalet,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
15071,1.00,"4,300,000.00",Penthouse,3,3,Cairo,New Cairo City,The 5th Settlement
15890,1.00,"5,800,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road
16012,1.00,"2,550,000.00",Chalet,3,2,Suez,Al Ain Al Sokhna,Coronado Beach

In [123]:
rent.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
34027,"305,000,000.00",Villa,"1,150.00",4,4,Cairo,New Cairo City,The 5th Settlement
32489,"185,000,000.00",Townhouse,260.00,4,5,Cairo,New Cairo City,South Investors Area
20125,"160,000,000.00",Villa,357.00,5,5,Giza,6 October City,Cairo Alexandria Desert Road
26743,"130,000,000.00",Townhouse,320.00,3,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
20581,"125,000,000.00",Townhouse,380.00,3,4,Giza,6 October City,Al Wahat Road
25709,"90,000,000.00",Townhouse,250.00,4,4,Cairo,New Cairo City,Ext North Inves Area
36506,"70,000,000.00",Apartment,122.00,2,2,Cairo,New Cairo City,The 5th Settlement
27943,"60,000,000.00",Palace,"2,500.00",7,7+,North Coast,Sidi Abdel Rahman,Marassi
36390,"28,113,558.00",Villa,800.00,4,5,Cairo,New Cairo City,Hyde Park
19731,"25,000,000.00",Twin House,279.00,4,4,Giza,Sheikh Zayed City,6th District
31635,"24,600,000.00",Townhouse,257.00,4,4,Cairo,New Cairo City,The 5th Settlement
36385,"21,085,812.00",Twin House,290.00,5,5,Cairo,New Cairo City,Hyde Park
25862,"18,620,000.00",Penthouse,235.00,3,3,Cairo,New Cairo City,South Investors Area
34679,"17,000,000.00",Apartment,205.00,3,3,Cairo,New Cairo City,The 5th Settlement
30529,"16,000,000.00",Apartment,211.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
22390,"15,890,000.00",Apartment,162.00,3,3,Cairo,New Cairo City,The 5th Settlement
22486,"15,000,000.00",Duplex,245.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
36669,"15,000,000.00",Villa,400.00,3,3,Cairo,New Cairo City,The 5th Settlement
26751,"14,500,000.00",Apartment,149.00,2,3,Cairo,New Cairo City,The 5th Settlement
30356,"14,500,000.00",Townhouse,385.00,5,5,Giza,6 October City,6 October Compounds

In [124]:
rent.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
19872,"1,300.00",Apartment,157.00,2,3,Cairo,New Cairo City,The 5th Settlement
19894,"1,400.00",Villa,180.00,3,3,Cairo,New Cairo City,The 5th Settlement
20362,"1,400.00",Apartment,210.00,3,3,Cairo,New Cairo City,The 5th Settlement
19893,"1,700.00",iVilla,278.00,4,3,Cairo,New Cairo City,The 5th Settlement
20943,"1,750.00",Apartment,170.00,2,4,Cairo,New Cairo City,North Investors Area
19870,"1,800.00",Apartment,268.00,3,3,Cairo,New Cairo City,The 5th Settlement
20207,"2,000.00",Villa,355.00,5,5,Cairo,New Cairo City,The 5th Settlement
19752,"2,200.00",Apartment,400.00,3,3,Cairo,New Cairo City,El Katameya
19868,"2,200.00",Apartment,190.00,3,3,Cairo,New Cairo City,The 5th Settlement
20026,"3,000.00",Apartment,70.00,3,1,Qalyubia,Shobra Al Khaimah,NaN
20418,"3,000.00",Apartment,96.00,2,2,Cairo,Madinaty,Privado
19758,"4,444.00",Apartment,70.00,1,1,Cairo,Madinaty,NaN
19989,"4,500.00",Apartment,80.00,2,1,Giza,6 October City,Al Wahat Road
20021,"4,800.00",Apartment,20.00,studio,1,Giza,6 October City,Al Hosary
19748,"5,000.00",Apartment,90.00,2,1,Cairo,Nasr City,1st Zone
19749,"5,000.00",Apartment,100.00,2,1,Cairo,Nasr City,6th Zone
19938,"5,500.00",Apartment,150.00,3,3,Cairo,Nasr City,6th Zone
21218,"5,600.00",Apartment,35.00,studio,1,Giza,6 October City,3rd District
21004,"6,000.00",Apartment,60.00,1,1,Cairo,Heliopolis - Masr El Gedida,Roxy
21153,"6,000.00",Apartment,200.00,3,2,Cairo,Nasr City,Masaken Al Mohandesin

In [125]:
rent.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
20349,"3,500.00","610,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District
25053,"3,000.00","625,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District
27081,"3,000.00","500,000.00",Villa,7,7+,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
26254,"2,700.00","386,000.00",Villa,5,7,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
26098,"2,500.00","700,000.00",Villa,7,7,Cairo,New Cairo City,El Katameya
27943,"2,500.00","60,000,000.00",Palace,7,7+,North Coast,Sidi Abdel Rahman,Marassi
28206,"2,500.00","900,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya
28224,"2,500.00","637,000.00",Villa,7+,7+,Cairo,New Cairo City,The 5th Settlement
28748,"2,400.00","260,000.00",Villa,6,7+,Giza,Sheikh Zayed City,4th District
35367,"2,400.00","275,000.00",Villa,7,7+,Giza,Sheikh Zayed City,4th District
19552,"2,000.00","576,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya
28201,"2,000.00","650,000.00",Villa,4,5,Cairo,New Cairo City,The 5th Settlement
28216,"2,000.00","800,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
28230,"2,000.00","833,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya
32303,"2,000.00","750,000.00",Palace,7+,7+,Cairo,New Cairo City,The 5th Settlement
35131,"2,000.00","350,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
29893,"1,920.00","850,000.00",Whole Building,7+,7+,Giza,Mohandessin,Ahmed Orabi St.
28232,"1,800.00","650,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya
30072,"1,800.00","410,000.00",Villa,7,7+,Giza,6 October City,Cairo Alexandria Desert Road
19441,"1,700.00","500,000.00",Villa,7+,6,Cairo,New Cairo City,El Katameya

In [126]:
rent.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
26184,1.00,"85,000.00",iVilla,3,3,Cairo,New Cairo City,The 5th Settlement
31194,6.00,"170,000.00",Villa,4,3,Cairo,New Cairo City,Hyde Park
20021,20.00,"4,800.00",Apartment,studio,1,Giza,6 October City,Al Hosary
29510,20.00,"18,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus
34933,20.00,"45,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
23787,25.00,"28,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
23795,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
24573,25.00,"30,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
25671,25.00,"15,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus
28804,25.00,"25,999.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
29561,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,6th District
30039,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
33296,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
34235,25.00,"31,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
35496,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
35731,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
37584,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
30755,26.00,"17,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
30759,26.00,"22,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
25010,27.00,"20,000.00",Penthouse,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds

## **bedrooms & bathrooms breaking down**

In [127]:
re['bedrooms'].value_counts(dropna=False)

bedrooms
3         17485
2          8958
4          5912
5          2063
1          1542
studio     1086
6           658
7           219
7+          182
NaN          33
Name: count, dtype: int64

In [128]:
re['bathrooms'].value_counts(dropna=False)

bathrooms
3       13619
2       10536
4        5932
1        4243
5        2371
6         770
7         376
7+        255
NaN        28
none        8
Name: count, dtype: int64

In [129]:
#Making bedrooms and bathrooms  Ordered Categorical

bed_order = ['studio', '1', '2', '3', '4', '5', '6', '7', '7+']
bath_order = ['none', '1', '2', '3', '4', '5', '6', '7', '7+']

for df in [sell, rent]:
    df['bedrooms'] = pd.Categorical(df['bedrooms'], categories=bed_order, ordered=True)
    df['bathrooms'] = pd.Categorical(df['bathrooms'], categories=bath_order, ordered=True)

In [130]:
#Adjusting data types
for dataframe in [rent, sell]:
  
  dataframe['listed_date'] = pd.to_datetime(dataframe['listed_date'])

  # Ensure agent_id and broker_id are treated as categorical/string IDs
  dataframe['agent_id'] = (
      dataframe['agent_id'].fillna(-1).astype(int).astype(str)
  )
  dataframe['broker_id'] = (
      dataframe['broker_id'].fillna(-1).astype(int).astype(str)
  )

## **Duplicated rows**

No duplicate listing IDs does NOT mean no duplicate properties/listings.

It means only that the IDs are unique.

In [131]:
re.duplicated().sum()

np.int64(0)

In [132]:
re['listing_id'].duplicated().sum()

np.int64(0)

In [133]:
duplicates_filter = ['property_type','completion_status','price_egp','city','town','district',
'lat','lon','bedrooms','bathrooms','area_value','furnished','listing_level','is_premium','is_featured'
,'payment_method','agent_id','broker_id'
      ]

In [134]:
re.duplicated(subset=duplicates_filter).sum()

np.int64(852)

## drop meaningless columns

In [135]:
# it has been dealeted last step
# sell.drop(columns=['price_period'],inplace=True,errors='ignor')# one value:sell
# rent.drop(columns=['price_period'], inplace=True, errors='ignore')# one value:monthly

# sell.drop(columns=['offering_type'],inplace=True,errors='ignore')# one value:Residential for Sale
# rent.drop(columns=['offering_type'],inplace=True,errors='ignore')# one value:Residential for rent

# sell.drop(columns=['category'],inplace=True,errors='ignore')# one value:buy
# rent.drop(columns=['category'],inplace=True,errors='ignore')# one value:rent

# sell.drop(columns=['rera'],inplace=True,errors='ignore')#NULL
# rent.drop(columns=['rera'],inplace=True,errors='ignore')#NULL

## **2 dataframs cleaning**

### dealing with wrong 'area_value' in rent dataframe

drop rows with less than 20m2 in rent as all of them is wrong

In [136]:
#investigate the sucpesious 'area_value'
(rent['area_value'] <= 20).sum()

np.int64(5)

In [137]:
rent = rent[rent['area_value'] > 20]

In [138]:
rent.shape

(19016, 19)

### dealing with wrong 'area_value' in sell dataframe

investigate the problematic rows

In [139]:
(sell['area_value'] <=20).sum()

np.int64(1343)

In [140]:
sell[(sell['area_value'] <=20)].head(100)

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
61,Villa,completed_primary,villa275m ready to move finished with DP1.8mil...,"1,800,000.00",Giza,6 October City,6th District,30.01,30.93,4,4,20.00,NO,premium,2026-03-04 12:06:03+00:00,cash,Ready-to-move-in fully finished standalone vil...,61112,6005
65,Villa,completed_primary,villa275m ready to move finished with DP1.8mil...,"1,800,000.00",Giza,6 October City,6 October Compounds,29.99,31.08,4,4,20.00,NO,premium,2026-03-04 12:04:40+00:00,cash,Ready-to-move-in fully finished standalone vil...,61112,6005
75,Apartment,completed_primary,ready to move finished Apt. 195m + 8Y Installment,"2,500,000.00",Giza,6 October City,6 October Compounds,29.91,30.67,3,3,20.00,PARTLY,premium,2025-12-21 11:32:20+00:00,cash,Immediate Delivery fully finished Apartment – ...,59409,1168
80,Villa,completed_primary,"luxury villa 229m + quarterly installment 610,000","610,000.00",Giza,Sheikh Zayed City,6th District,30.04,30.99,4,4,1.00,NaN,premium,2026-03-04 11:08:44+00:00,cash,Townhouse in a Prime Location on 26th of July ...,59409,1168
138,Apartment,completed_primary,Apartment 134m² (finished and ready for handover),"900,000.00",North Coast,Al Alamein,Marina,30.84,28.97,1,1,20.00,NO,premium,2026-02-25 12:21:03+00:00,cash,"For Sale in Lower Egypt, in the Latin District...",42206,3655
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,Apartment,completed_primary,"With a 5% down payment of only 178,000, you ca...","356,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,3,2,20.00,NaN,premium,2026-02-24 11:50:44+00:00,cash | installments,"With a 5% down payment of only 178,000, you ca...",64923,531
1513,Apartment,completed_primary,"DP1, 2M=Hot deal apt170sqm, special price, ready","1,200,000.00",Cairo,New Cairo City,The 1st Settlement,30.09,31.51,3,3,20.00,NaN,premium,2026-02-22 22:17:51+00:00,cash,Ready for viewing now - Immediate occupancy Op...,70922,3655
1554,Chalet,completed_primary,"790,000 EGP = Rtm Sea View Fully Finished chal...","790,000.00",Suez,Al Ain Al Sokhna,IL Monte Galala,29.50,32.41,3,2,20.00,NO,premium,2026-02-23 18:21:57+00:00,cash | installments,"119m Panoramic Sea View 100% Fully Finished ,a...",70902,3655
1558,Apartment,completed_primary,1 millon Radytomove-Fullyfinshed in Sheraton,"1,000,000.00",Cairo,El Nozha,Sheraton Al Matar,30.09,31.38,2,2,20.00,NO,premium,2026-02-22 19:41:12+00:00,cash,Receive your fully finished apartment immediat...,70950,3655
1560,Apartment,completed_primary,only 1 millon 50mgarden - radytomove130m,"1,000,000.00",Cairo,New Cairo City,The 1st Settlement,30.09,31.51,2,2,20.00,NO,premium,2026-02-21 20:55:37+00:00,cash,Luxury apartment ready for immediate occupancy...,70950,3655

In [141]:
# making sure the suspicious area values are the same in original dataframe
(re['area_value'] <=20).sum() # 1457 in sell + 5 in rent = 1462 in re

np.int64(1348)

In [142]:
# temporary dataframe that contains all properties with area <=20
small_sell = sell[sell['area_value'] <= 20].copy()

print("Number of suspicious sale records:", len(small_sell))

print("\nProperty types:")
print(small_sell['property_type'].value_counts())

print("\nArea distribution:")
print(small_sell['area_value'].value_counts().sort_index())

Number of suspicious sale records: 1343

Property types:
property_type
Apartment          781
Villa              316
Chalet             164
Penthouse           27
Duplex              22
Hotel Apartment     16
Twin House          11
iVilla               3
Whole Building       2
Palace               1
Name: count, dtype: int64

Area distribution:
area_value
1.00       22
2.00        6
3.00        1
5.00        3
6.00        1
10.00      32
11.00       3
12.00       1
14.00       3
15.00       2
16.00       1
17.00       1
20.00    1267
Name: count, dtype: int64

In [143]:
pd.crosstab(
    small_sell['property_type'],
    small_sell['area_value']
)

area_value,1.00,2.00,3.00,5.00,6.00,10.00,11.00,12.00,14.00,15.00,16.00,17.00,20.00
property_type,,,,,,,,,,,,,
Apartment,0,0,0,0,0,0,0,0,0,0,0,0,781
Chalet,5,5,0,3,0,18,3,0,2,2,1,1,124
Duplex,1,0,0,0,0,0,0,0,0,0,0,0,21
Hotel Apartment,4,0,1,0,0,4,0,0,0,0,0,0,7
Palace,1,0,0,0,0,0,0,0,0,0,0,0,0
Penthouse,2,0,0,0,0,1,0,0,0,0,0,0,24
Twin House,1,0,0,0,0,0,0,0,0,0,0,0,10
Villa,8,1,0,0,1,9,0,1,1,0,0,0,295
Whole Building,0,0,0,0,0,0,0,0,0,0,0,0,2
iVilla,0,0,0,0,0,0,0,0,0,0,0,0,3

In [144]:
#summation of titles in the new dataframe that contains the real area
small_sell['title'].str.extract(
    r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b',
    expand=False
).notna().sum()

np.int64(585)

In [145]:
#show rows where titles contains the real area
small_sell[
    small_sell['title'].str.extract(
        r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b',
        expand=False
    ).notna()
][
    ['property_type', 'area_value', 'title']
].head(50)

,property_type,area_value,title
61,Villa,20.00,villa275m ready to move finished with DP1.8mil...
65,Villa,20.00,villa275m ready to move finished with DP1.8mil...
75,Apartment,20.00,ready to move finished Apt. 195m + 8Y Installment
80,Villa,1.00,"luxury villa 229m + quarterly installment 610,000"
138,Apartment,20.00,Apartment 134m² (finished and ready for handover)
155,Villa,20.00,Villa 757m Lowest price /Quarterly 827K Palm H...
157,Apartment,20.00,Ready-to-Move Garden Apartment160m per Q463K i...
159,Villa,20.00,Ready to move Villa220m Pool View 1.400M Quart...
163,Apartment,20.00,Apartment165m ReadytoMove Lagoons View Install...
168,Villa,20.00,Villa 522m ReadytoMove at Old Price on Install...
171,Villa,20.00,Villa540m 7Rooms on Instllment Behind MallofAr...
173,Apartment,20.00,Apartment 206m 806K DP With Longest Payment Plan
174,Villa,20.00,Villa538m with Pool Instllment Behind MallofAr...
175,Apartment,20.00,Ready to Move Aprtmnt 148m Resale Price Instal...
184,Penthouse,20.00,Last 275 m² 4-bd Zayed Near Ahly club Over14 y...
202,Apartment,20.00,"206m 3 rooms ,Service Aprtment Zayed over 10 y..."
203,Apartment,20.00,"Last 164 m, 3bd +large garden ReadyToMove inst..."
250,Apartment,20.00,Finished APt100m DP360.000 15Y installments Op...
251,Apartment,20.00,164m Finished Apartment New Cairo 650K Quarterly
391,Apartment,20.00,Apt130m finished ready to move with DP 2.2million
456,Apartment,20.00,Prime deal 130m garden apt near Mall of Arabia
475,Apartment,20.00,Last 164m² 3 bd View Pool ReadyTo Move +installme
518,Apartment,20.00,Apartment 140m + Garden ( Fully Finished ) RTM
562,Apartment,20.00,Cheapest apartment196m ready to move in 6 West
584,Chalet,10.00,"Finished 100m, Lake view, Lowest DP, till 2032"
660,Apartment,20.00,RTM Apartment171m at Landscape View on Install...
668,Apartment,20.00,Apart160m FullyFinish ReadytoMove in Zayed on ...
670,Apartment,20.00,Apart171m FullyFinishd & ACs+Ktchen Hotel Serv...
673,Villa,20.00,Villa 565m FullyFnish Ready to Move on Install...
716,Apartment,20.00,Ready To Move AP 138m With Discount 34% Or DP ...
794,Villa,20.00,Lowest price Villa 332m Finished Palm Hills+in...
797,Apartment,20.00,"DP 1500K,apartment(140m+garden)(RTM)-mountain ..."
798,Chalet,20.00,FinishedFinished+ACs Ch148m Amazing Sea View D...
800,Villa,20.00,Panoramic Sea View On Elevation 160m Ready Vie...
804,Duplex,20.00,"1,600,000 Only! Ready To Move Duplex 195m VIP ..."
805,Villa,20.00,"DP 1,000,000 Villa 150m Sea View Or Discount 4..."
806,Chalet,2.00,Cash Discount 40% Chalet 181m Direct Sea View
807,Chalet,10.00,"1,500,000= Chalet 182m + G First Row Steps To Sea"
808,Apartment,20.00,Ready To Move & Finished Apartment 154m Corner
809,Villa,20.00,Lowest Price 373m Villa in Sheikh Zayed near H...
811,Apartment,20.00,DP 600k=apt(100m+garden 118m+pool) finished-ta...
812,Apartment,20.00,DP(420k)=APT(199m+garden72m)from the Saudi Com...
814,Apartment,20.00,"DP 690k,apartment(132m),garden view,before mar..."
825,Apartment,20.00,"APT,195m finished with DP 1.8 million ,prime view"
828,Apartment,20.00,"Apt 205m finished+A,C with DP 1.4million prim ..."
1031,Chalet,20.00,Chalet Resale Panorama View 90m +R Finished Ma...
1103,Apartment,20.00,Apartment172m FullyFinish ReadytoMove Installment
1130,Villa,20.00,Villa373m in Sheikh Zayed-Lowest Price-Pool View
1154,Villa,20.00,350m Villa with Open View near Palm Hills –inst
1209,Apartment,20.00,Beit Al Watan-147 m- installments over 72 months

In [146]:
# create new column with the extracted area
small_sell['area_from_title'] = (
    small_sell['title']
    .str.extract(r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b', expand=False)
    .astype(float))

In [147]:
small_sell['area_from_title'].shape # 1457 row (number of area <=20)

(1343,)

In [148]:
print(small_sell['area_value'].isna().sum())

#number of area that will be recovered
print(small_sell['area_value'].notna().sum())

0
1343

In [149]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
].sort_values().head(20)

7745     50.00
12809    71.00
17399    84.00
1031     90.00
17633    90.00
8892     95.00
2946     95.00
6781     96.00
17626    96.00
9621     99.00
9588     99.00
7187    100.00
10700   100.00
16577   100.00
811     100.00
7085    100.00
12908   100.00
7074    100.00
584     100.00
7084    100.00
Name: area_from_title, dtype: float64

In [150]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
].sort_values().tail(20)

17981   377.00
18033   377.00
18002   377.00
17974   377.00
17987   377.00
18302   400.00
18322   400.00
8067    400.00
15068   420.00
168     522.00
174     538.00
171     540.00
673     565.00
18890   565.00
1960    566.00
16442   643.00
9188    757.00
155     757.00
12912   757.00
9191    757.00
Name: area_from_title, dtype: float64

In [151]:
#the extract is almost true as range of values is normal
print(small_sell.shape)

print(small_sell['area_from_title'].notna().sum())

print(small_sell['area_from_title'].dtype)

print(small_sell['area_from_title'].describe())

(1343, 20)
585
float64
count   585.00
mean    207.87
std      97.18
min      50.00
25%     140.00
50%     180.00
75%     242.00
max     757.00
Name: area_from_title, dtype: float64

In [152]:
# check if the most big area values match the property type
small_sell[
    small_sell['area_from_title'] > 500
][
    ['property_type', 'area_value', 'area_from_title', 'title']
]

,property_type,area_value,area_from_title,title
155,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
168,Villa,20.00,522.00,Villa 522m ReadytoMove at Old Price on Install...
171,Villa,20.00,540.00,Villa540m 7Rooms on Instllment Behind MallofAr...
174,Villa,20.00,538.00,Villa538m with Pool Instllment Behind MallofAr...
673,Villa,20.00,565.00,Villa 565m FullyFnish Ready to Move on Install...
1960,Villa,20.00,566.00,566m Villa 5-Settlement Finished By Palm Hills 9y
9188,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
9191,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
12912,Villa,20.00,757.00,Prime villa( 757m+3floors+open view+ full priv...
16442,Villa,20.00,643.00,"Fully finished 643m² standalone villa, lagoon ..."
18890,Villa,20.00,565.00,Villa 565m Ready to Move on Installment in SODIC

In [153]:
# number of biggest area values
(small_sell['area_from_title'] > 500).sum()

np.int64(11)

 merge the extracted column in the sell dataframe

In [154]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_value'
] = small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
]

In [155]:
small_sell.loc[
    small_sell['area_from_title'].isna(),
    'area_value'
] = np.nan

In [156]:
sell['area_status'] = 'Original'

In [157]:
# merg 'area_from_title' with 'area_value' in 'area_status'
recovered = small_sell['area_from_title'].notna()

sell.loc[
    small_sell.index[recovered],
    'area_value'
] = small_sell.loc[
    recovered,
    'area_from_title'
]

In [158]:
# label area values that coudn't be recovered as 'unknown'
unknown = small_sell['area_from_title'].isna()

sell.loc[
    small_sell.index[unknown],
    'area_value'
] = np.nan

sell.loc[
    small_sell.index[unknown],
    'area_status'
] = 'Unknown'

In [159]:
#label 'area_value' that could be recoverd as recovered in 'area_status'
sell.loc[
    small_sell.index[recovered],
    'area_status'
] = 'Recovered'

In [160]:
(sell['area_value'] <= 20).sum()

np.int64(0)

In [161]:
#
(sell['area_status'] == 'Unknown').sum()

np.int64(758)

In [162]:
# drop rows that can't be extracted from title
sell = sell[sell['area_status'] != 'Unknown'].copy()

### wrong listed properties

properties for rent listed in sell dataframe

In [163]:
#Is price_egp always the actual sale price,
#or is it sometimes an installment/down-payment/displayed payment amount?

re[re['title'].str.contains(
    'quarter|monthly|down payment|installment|cash',
    case=False,
    na=False
)][[
    'price_egp',
    'price_period',
    'title'
]].head(30)

,price_egp,price_period,title
9,"23,250,000.00",sell,Swan Lake Gouna’s Last Unit — Flexible Install...
31,"6,500,000.00",sell,ready to move finished apt. 205m+148m installment
51,"450,000.00",sell,fully finished unit with ACs 153m-445K per qua...
64,"16,700,000.00",sell,Twinhouse for sale RTM -cash- very prime location
75,"2,500,000.00",sell,ready to move finished Apt. 195m + 8Y Installment
80,"610,000.00",sell,"luxury villa 229m + quarterly installment 610,000"
85,"130,000.00",sell,duplex in zayed with 130K per quarter-unit 233 m
87,"130,000.00",sell,duplex in zayed with 130K per quarter-unit 233 m
95,"8,700,000.00",sell,Chalet Opportunity With 0% Dp And Installments...
99,"3,370,500.00",sell,"""1-Bedroom Apartment in Ibiza – Down Payment 4..."
117,"8,700,000.00",sell,Rady for viewing and deliver finished installm...
124,"6,690,000.00",sell,"Apartment for sale with a down payment of 670,000"
127,"5,000,000.00",sell,APT + Garden over 15Y installments or 40% cash...
129,"11,900,000.00",sell,apartment 4 Bed with DP&installments- 238 SQM
133,"7,000,000.00",sell,"Apartment for sale with a down payment of 107,000"
134,"5,500,000.00",sell,"Apartment for sale in a garden, down payment 5..."
143,"37,600,000.00",sell,Villa with a 1.5% down payment + installments ...
144,"10,989,000.00",sell,144m² fully finished chalet in the Latin Quart...
145,"6,443,000.00",sell,Studio apartment for sale with a down payment ...
146,"7,000,000.00",sell,With700K dp from New Cairo near CFC installment
155,"827,000.00",sell,Villa 757m Lowest price /Quarterly 827K Palm H...
159,"1,428,824.00",sell,Ready to move Villa220m Pool View 1.400M Quart...
162,"3,000,000.00",sell,Apart182m FullyFinished ReadytoMove on Install...
163,"1,197,000.00",sell,Apartment165m ReadytoMove Lagoons View Install...
168,"6,200,000.00",sell,Villa 522m ReadytoMove at Old Price on Install...
172,"3,000,000.00",sell,villa 352m open view near palm hills + install...
176,"3,000,000.00",sell,finished apartment 180m with A\C +8yrs install...
178,"4,600,000.00",sell,"Ready apartment 170 m at lowest price, install..."
186,"3,659,400.00",sell,Chalet 57m on the sea with 4year installments
223,"300,000.00",sell,"120m finished chalet ,Marina view300K per quarter"

In [164]:
#1489 value in the original data
(re['title'].str.contains(
    'quarter|monthly|quarterly|down payment|installment|cash',
    case=False,
    na=False
)).sum()

np.int64(1402)

In [165]:
# new temporary dataframe
wrong_rent_in_sell = sell[
    sell['title'].str.contains(
        r'for rent|monthly rent|quarterly rent|per month|per quarter',case=False,na=False,regex=True
    )
]

In [166]:
wrong_rent_in_sell.shape #(9, 22)

(9, 20)

In [167]:
wrong_rent_in_sell[
    ['price_egp','property_type','area_value','city','town','district','title']
].head(30)

,price_egp,property_type,area_value,city,town,district,title
51,"450,000.00",Apartment,153.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,fully finished unit with ACs 153m-445K per qua...
85,"130,000.00",Duplex,233.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,duplex in zayed with 130K per quarter-unit 233 m
87,"130,000.00",Apartment,233.00,Giza,Sheikh Zayed City,Ivoire,duplex in zayed with 130K per quarter-unit 233 m
223,"300,000.00",Chalet,120.00,Suez,Al Ain Al Sokhna,IL Monte Galala,"120m finished chalet ,Marina view300K per quarter"
497,"113,116.00",Apartment,155.00,Giza,6 October City,6 October Compounds,Finished Apartment155m+Garden for 113K per Qua...
2021,"474,525.00",Apartment,225.00,Giza,6 October City,6 October Compounds,RTM Finished iVilla 225m+Garden-474K per Quarter
2134,"155,220.00",Apartment,200.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Pay 52K per month&Get Finished Apartment in Zayed
2338,"5,500,000.00",Apartment,150.00,Alexandria,Hay Sharq,Smouha,"Apartment for rent, 210 sq m, Smouha (Grand View)"
8414,"8,000,000.00",Apartment,130.00,Cairo,New Cairo City,South Investors Area,Apartment for rent or sale in Galleria Moon Va...

In [168]:
sell = sell.drop(index=wrong_rent_in_sell.index, errors='ignore')

properties for sell listed in rent dataframe

In [169]:
# new temporary dataframe
wrong_sell_in_rent = rent[
    rent['title'].str.contains(
        r'for sell|sell|sale',case=False,na=False,regex=True
    )
]

In [170]:
wrong_sell_in_rent[
    ['price_egp','property_type','area_value','city','town','district','title'
    ]
].head(30)

,price_egp,property_type,area_value,city,town,district,title
19313,"55,000.00",Apartment,186.00,Cairo,New Cairo City,The 5th Settlement,Apartment sale - Semi Furnished - Mivida
19434,"110,000.00",Villa,"1,000.00",Cairo,New Cairo City,Ext North Inves Area,Bellagio-semi Furnished Standalone 1000m For Sale
19460,"200,000.00",Villa,225.00,Cairo,New Cairo City,The 5th Settlement,VILLA 750M SALE IN MV1 WITH KITCHEN & ACS
19731,"25,000,000.00",Twin House,279.00,Giza,Sheikh Zayed City,6th District,Villa for sale - Greens Compound - Sheikh Zayed
20074,"15,000.00",Apartment,96.00,Cairo,Madinaty,Privado,Apartment 96m for sale in madinaty at B7
20377,"40,000.00",Apartment,150.00,Cairo,Hay El Manial,El Roda,"Apartment for rent, 150 sq m, King Saleh Stree..."
20805,"215,100.00",Apartment,327.00,Giza,Ganoub El Giza,Giza District,Luxury 5 Star Nile Apartment For Sale or Rent
20813,"215,000.00",Apartment,326.00,Giza,Dokki,Nile St.,Luxury 5 Star Nile Apartment For Sale or Rent
20818,"223,700.00",Apartment,297.00,Giza,Dokki,Nile St.,Nile serviced flat modern finish sale/rent 290m
20827,"7,750,000.00",Apartment,180.00,Cairo,New Cairo City,Al Narges,Ultra Super Lux Apartment for Sale with a Larg...
20944,"14,000.00",Apartment,103.00,Cairo,Madinaty,Privado,Apartment 103m for sale in madinaty at B6
21906,"10,000,000.00",Apartment,186.00,Cairo,New Cairo City,The 5th Settlement,Apartment for sale in Amorada With Fully AC'S
21960,"11,000,000.00",Apartment,216.00,Cairo,New Cairo City,Hyde Park,Apartment for Sale in Hyde Park - New Cairo
22640,"55,000.00",Apartment,235.00,Cairo,New Cairo City,The 5th Settlement,Ground Floor Apartment with Garden for Sale in...
22859,"100,000.00",Apartment,215.00,Cairo,New Cairo City,North Investors Area,Apartment for Sale or Rent in The Waterway Res...
22988,"75,000.00",Apartment,210.00,Cairo,New Cairo City,The 5th Settlement,Apartment for Sale in District 5 – Prime Location
23746,"8,000,000.00",Apartment,160.00,Cairo,New Cairo City,The 5th Settlement,Apartment for Sale in Prime Location at Park R...
23814,"145,000.00",Apartment,235.00,Cairo,New Cairo City,North Investors Area,Fully Furnished Apartment for sale in water way 1
24229,"192,000.00",Twin House,404.00,Cairo,New Cairo City,El Katameya,Luxury Twin Villa for Sale & Rent in Katameya ...
24981,"5,500,000.00",Apartment,185.00,Cairo,Nasr City,8th Zone,Apartment for sale in a prime location on Shinsoo
25005,"6,000,000.00",Apartment,210.00,Cairo,Nasr City,6th Zone,Apartment for sale in a prime location near Ma...
25542,"20,000.00",Apartment,143.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Apartment for sale with private garden.
25709,"90,000,000.00",Townhouse,250.00,Cairo,New Cairo City,Ext North Inves Area,Town House for sale in Dyar Park FF with AC's & K
25859,"128,000.00",Townhouse,285.00,Cairo,New Cairo City,The 5th Settlement,285sqm Resale Apt | Mivida | Great Price
25862,"18,620,000.00",Penthouse,235.00,Cairo,New Cairo City,South Investors Area,Penthouse for Sale in Golden Square – Galleria...
26151,"8,350,000.00",Apartment,160.00,Cairo,New Cairo City,The 5th Settlement,For Sale Fully Finished Penthouse in Trio Gardens
26305,"130,000.00",Villa,325.00,Cairo,New Cairo City,The 5th Settlement,Luxurious 4 Bedroom 325m² Villa for Sale in mi...
26751,"14,500,000.00",Apartment,149.00,Cairo,New Cairo City,The 5th Settlement,Apartment with garden for sale in District 5
26827,"193,000.00",Apartment,330.00,Cairo,Zamalek,Kamal Al Tawil St. (El Montazah),5-Star Nile-Facing Serviced Apartment for Sale...
26831,"193,100.00",Apartment,231.00,Cairo,Zamalek,Mohamed Abdel Wahab St.,5-Star Nile-Facing Serviced Apartment for Sale...

In [171]:
wrong_sell_in_rent.shape

(96, 19)

In [172]:
# properties for rent or sell in rent datafram
wrong_sell_in_rent['title'].str.contains(
    r'for sale or rent|sale/rent|sale & rent|for sale and rent',
    case=False,
    na=False,
    regex=True
).sum() # 20

# only 20 of properties for sell that is listed in rent df are for both rent and sell

np.int64(20)

In [173]:
#drop the 96 worng raw
rent = rent.drop(index=wrong_sell_in_rent.index)

### suspicious price

dealing with very low price listings in sell

In [174]:
very_low_sell = sell[(sell['price_egp'] < 300000)& (sell['area_value'] >120)]

very_low_sell[
    ['price_egp', 'property_type', 'area_value',
     'city', 'town', 'district', 'title']
]

Empty DataFrame
Columns: [price_egp, property_type, area_value, city, town, district, title]
Index: []

dealing with very low price listings in rent

In [175]:
very_low_rent = rent[
    (rent['price_egp'] < 3000) &
    (rent['area_value'] > 120) &
    (rent['property_type'].isin(['iVilla', 'Villa']))
]

# Display specific columns
very_low_rent[['price_egp', 'property_type', 'area_value', 'city', 'town', 'district', 'title']]

,price_egp,property_type,area_value,city,town,district,title
19893,"1,700.00",iVilla,278.00,Cairo,New Cairo City,The 5th Settlement,Apartment for rent 4bedroom in MV Hyde park
19894,"1,400.00",Villa,180.00,Cairo,New Cairo City,The 5th Settlement,Villa for rent 3bedroom in Mountain View i city
20207,"2,000.00",Villa,355.00,Cairo,New Cairo City,The 5th Settlement,Premium Villa with private pool in Mivida

In [176]:
rent = rent.drop(index=very_low_rent.index)

In [178]:
rent['furnished'].isna().sum()

np.int64(112)

In [190]:
#Filling the completion_status in the rent ste
rent.drop(columns=['completion_status'],inplace=True,errors='ignore')
rent.drop(columns=['payment_method'],inplace=True,errors='ignore')

In [180]:
sell['district'] = sell['district'].fillna(sell['town'])
rent['district'] = rent['district'].fillna(rent['town'])

In [ ]:
sell['price_per_sqm'] = sell['price_egp'] / sell['area_value']
rent['price_per_sqm'] = rent['price_egp'] / rent['area_value']

In [193]:
sell.to_csv('Sell.csv', index=False)
rent.to_csv('Rent.csv', index=False)

In [192]:
rent.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18917 entries, 19117 to 38137
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  18917 non-null  object
 1   title          18917 non-null  object
 2   price_egp      18917 non-null  float64
 3   city           18917 non-null  object
 4   town           18917 non-null  object
 5   district       18917 non-null  object
 6   lat            18917 non-null  float64
 7   lon            18917 non-null  float64
 8   bedrooms       18914 non-null  category
 9   bathrooms      18917 non-null  category
 10  area_value     18917 non-null  float64
 11  furnished      18805 non-null  object
 12  listing_level  18917 non-null  object
 13  listed_date    18917 non-null  datetime64[ns, UTC]
 14  description    18917 non-null  object
 15  agent_id       18917 non-null  object
 16  broker_id      18917 non-null  object
dtypes: category(2), datetime64[ns, UTC](1), float64(4), object(10)
memory usage: 2.3+ MB